services:
  - type: web
    name: deadpracticesite
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    plan: free
